logging:
  path: ./log/

spring:
  datasource:
    #    通过容器名称beeMysql 连接mysql
    url: jdbc:mysql://47.109.96.250:3306/bee?useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: mfox
    password: 798541
    driver-class-name: com.mysql.cj.jdbc.Driver