spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    filters: wall,mergeStat
    type: com.alibaba.druid.pool.DruidDataSource