spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bee?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: mfox
    password: 798541
    filters: wall,mergeStat
    type: com.alibaba.druid.pool.DruidDataSource